vg: vgtomcat
harddisk: /dev/sdb
mowner: tomcat9
lv1: lvol_tomcat
lv2: lvo2_tomcat
lv3: lvo3_tomcat
size1: 25g
size2: 30g
size3: 35g
mp1: /var/log/service
mp2: /var/lib/tomcat9
mp3: /var/log/tomcat9
jenkins_user: jenkins
jenkins_password: jenkins
src_policy_jar: local_policy.jar
webapps_path: /var/lib/tomcat9/webapps
varlogservice_path: /var/lib/tomcat9/webapps
tomcat8_src_tcsystemdxml: tomcat8.service
tomcat9_src_tcsystemdxml: tomcat9.service
src_jdbclibrariesxml: jdbclibraries.tar.gz
src_us_export_policy: US_export_policy.jar
java_JDK11: java-11-openjdk-devel
Ubuntu_JDK8: openjdk-8-jdk
Ubuntu_JDK11: openjdk-11-jdk
RedHat_JDK8: java-1.8.0-openjdk-devel
Ubuntu_Resolv_conf: ubuntu_resolv.conf
